" general {{{
syntax on
let g:vim_data_path = expand("$HOME") . "/.vim/data/"
let g:JSLintHighlightErrorLine = 0
" }}}
" fish {{{
if $SHELL =~ 'bin/fish'
    set shell=/bin/sh
endif
" }}}
" leader {{{
let mapleader = ","
let maplocalleader = "\\"
" }}}
" startup {{{
" vundle
filetype off
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
source ~/.vim/startup/bundle.vim
filetype plugin indent on
" other scripts
source ~/.vim/startup/options.vim
source ~/.vim/startup/plugins.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/autocmd.vim
" }}}
" colorscheme {{{
set t_Co=256
" set background=dark
colorscheme desert
" }}}
" if cwd is ~ change it to ~/works {{{
if getcwd() == expand('$HOME')
    cd ~/workspace
endif
" }}}
