# Emacs
PATH="$PATH:$HOME/.local/bin"

# Ruby
PATH="$PATH:$HOME/.rvm/bin"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# Android SDK
PATH="$PATH:$HOME/android/sdk/platform-tools"
PATH="$PATH:$HOME/android/sdk/tools"
ANDROID_HOME="$HOME/android/sdk/"
